"""
SafeRoute AI - Government Report Page
=====================================
Generate PDF reports and submit to municipality.
"""

import streamlit as st
from datetime import datetime, timedelta
from io import BytesIO

from fpdf import FPDF

from config import (
    APP_NAME, TEAM_NAME, CITY_NAMES, DEFAULT_CITY, SEVERITY_COLORS
)
from utils.data import filter_hazards, compute_stats, hazards_to_dataframe


class ReportPDF(FPDF):
    """Custom PDF class for SafeRoute AI reports."""
    
    def header(self):
        # Title
        self.set_font('Arial', 'B', 16)
        self.set_text_color(11, 31, 58)  # Navy
        self.cell(0, 10, f"{APP_NAME} - Road Hazard Report", 0, 1, 'C')
        
        # Line
        self.set_draw_color(13, 148, 136)  # Teal
        self.set_line_width(1)
        self.line(10, 25, 200, 25)
        
        self.ln(10)
    
    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f"Page {self.page_no()}", 0, 0, 'C')
        self.cell(0, 10, f"Generated on {datetime.now().strftime('%Y-%m-%d %H:%M')}", 0, 0, 'R')


def generate_pdf_report(hazards, city, date_range, severity_filter, reporter_name):
    """Generate a PDF report from hazard data."""
    
    # Filter hazards
    days = int(date_range.split()[0])
    start_date = datetime.now() - timedelta(days=days)
    
    filtered = filter_hazards(
        hazards,
        city=city if city != "All India" else None,
        severity=severity_filter if severity_filter else None,
        start_date=start_date
    )
    
    # Compute stats
    stats = compute_stats(filtered)
    
    # Create PDF
    pdf = ReportPDF()
    pdf.add_page()
    
    # ========== REPORT INFO ==========
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, f"Report Generated By: {reporter_name}", 0, 1)
    pdf.cell(0, 10, f"City: {city}", 0, 1)
    pdf.cell(0, 10, f"Date Range: Last {date_range}", 0, 1)
    pdf.cell(0, 10, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", 0, 1)
    
    pdf.ln(5)
    
    # ========== SUMMARY TABLE ==========
    pdf.set_font('Arial', 'B', 14)
    pdf.set_text_color(11, 31, 58)
    pdf.cell(0, 10, "Summary", 0, 1)
    
    pdf.set_font('Arial', '', 11)
    pdf.set_text_color(0)
    
    # Summary stats
    pdf.cell(60, 8, f"Total Hazards:", 0, 0)
    pdf.cell(40, 8, f"{stats['total_hazards']}", 0, 1)
    
    pdf.cell(60, 8, "High Severity:", 0, 0)
    pdf.cell(40, 8, f"{stats['high_severity_count']}", 0, 1)
    
    pdf.cell(60, 8, "Fixed:", 0, 0)
    pdf.cell(40, 8, f"{stats['fixed_count']}", 0, 1)
    
    pdf.cell(60, 8, "Active Issues:", 0, 0)
    pdf.cell(40, 8, f"{stats['active_issues']}", 0, 1)
    
    pdf.ln(5)
    
    # ========== SEVERITY BREAKDOWN ==========
    pdf.set_font('Arial', 'B', 14)
    pdf.set_text_color(11, 31, 58)
    pdf.cell(0, 10, "By Severity", 0, 1)
    
    pdf.set_font('Arial', '', 11)
    pdf.set_text_color(0)
    
    for severity, count in stats["by_severity"].items():
        pdf.cell(60, 8, f"{severity}:", 0, 0)
        pdf.cell(40, 8, f"{count}", 0, 1)
    
    pdf.ln(5)
    
    # ========== TYPE BREAKDOWN ==========
    pdf.set_font('Arial', 'B', 14)
    pdf.set_text_color(11, 31, 58)
    pdf.cell(0, 10, "By Type", 0, 1)
    
    pdf.set_font('Arial', '', 11)
    pdf.set_text_color(0)
    
    for htype, count in stats["by_type"].items():
        pdf.cell(60, 8, f"{htype}:", 0, 0)
        pdf.cell(40, 8, f"{count}", 0, 1)
    
    pdf.ln(10)
    
    # ========== TOP HAZARDS TABLE ==========
    pdf.set_font('Arial', 'B', 14)
    pdf.set_text_color(11, 31, 58)
    pdf.cell(0, 10, "Top 10 Hazards", 0, 1)
    
    # Table header
    pdf.set_font('Arial', 'B', 9)
    pdf.set_fill_color(11, 31, 58)  # Navy
    pdf.set_text_color(255, 255, 255)
    
    pdf.cell(25, 8, "ID", 1, 0, 'C', True)
    pdf.cell(35, 8, "Type", 1, 0, 'C', True)
    pdf.cell(25, 8, "Severity", 1, 0, 'C', True)
    pdf.cell(35, 8, "City", 1, 0, 'C', True)
    pdf.cell(25, 8, "Status", 1, 0, 'C', True)
    pdf.cell(25, 8, "Confidence", 1, 1, 'C', True)
    
    # Table rows
    pdf.set_font('Arial', '', 8)
    pdf.set_text_color(0)
    
    top_hazards = sorted(filtered, key=lambda x: (x.severity == "High", x.confidence), reverse=True)[:10]
    
    for hazard in top_hazards:
        # Alternate row colors
        if hazard.severity == "High":
            pdf.set_fill_color(254, 226, 226)  # Light red
        elif hazard.severity == "Medium":
            pdf.set_fill_color(254, 243, 199)  # Light amber
        else:
            pdf.set_fill_color(240, 253, 244)  # Light green
        
        pdf.cell(25, 7, hazard.id[:12], 1, 0, 'C', True)
        pdf.cell(35, 7, hazard.hazard_type[:15], 1, 0, 'C', True)
        pdf.cell(25, 7, hazard.severity, 1, 0, 'C', True)
        pdf.cell(35, 7, hazard.city[:15], 1, 0, 'C', True)
        pdf.cell(25, 7, hazard.status[:12], 1, 0, 'C', True)
        pdf.cell(25, 7, f"{hazard.confidence:.0%}", 1, 1, 'C', True)
    
    pdf.ln(10)
    
    # ========== FOOTER ==========
    pdf.set_font('Arial', 'I', 8)
    pdf.set_text_color(128)
    pdf.cell(0, 10, f"Report generated by {APP_NAME} | {TEAM_NAME} | CODE 1 Hackathon 2026", 0, 1, 'C')
    
    return pdf.output(dest='S').encode('latin-1')


def show():
    """Display the government report page."""
    
    # Page header
    st.markdown("""
    <div class="page-header">
        <h1>📄 Government Report</h1>
        <p class="subtitle">Generate and submit official road hazard reports</p>
    </div>
    <hr>
    """, unsafe_allow_html=True)
    
    # Get hazards from session state
    hazards = st.session_state.get("hazards", [])
    
    if not hazards:
        st.warning("No hazard data available. Please analyze some images first.")
        return
    
    # ========== REPORT FORM ==========
    st.markdown("### Generate Report")
    
    with st.form("report_form"):
        col1, col2 = st.columns(2)
        
        with col1:
            reporter_name = st.text_input(
                "Reporter Name",
                placeholder="Enter your name",
                help="Name of the person generating this report"
            )
        
        with col2:
            report_city = st.selectbox(
                "City",
                options=["All India"] + CITY_NAMES,
                index=0
            )
        
        col3, col4 = st.columns(2)
        
        with col3:
            date_range = st.selectbox(
                "Date Range",
                options=["7 days", "14 days", "30 days"],
                index=2
            )
        
        with col4:
            severity_filter = st.multiselect(
                "Filter by Severity",
                options=["High", "Medium", "Low"],
                default=["High", "Medium", "Low"]
            )
        
        # Generate button
        generate_btn = st.form_submit_button("📄 Generate PDF Report", type="primary")
    
    # ========== GENERATE AND DISPLAY ==========
    if generate_btn:
        if not reporter_name:
            st.error("Please enter your name")
        else:
            with st.spinner("Generating PDF report..."):
                try:
                    pdf_bytes = generate_pdf_report(
                        hazards=hazards,
                        city=report_city,
                        date_range=date_range,
                        severity_filter=severity_filter,
                        reporter_name=reporter_name
                    )
                    
                    st.success("✅ PDF Report generated successfully!")
                    
                    # Show preview stats
                    days = int(date_range.split()[0])
                    start_date = datetime.now() - timedelta(days=days)
                    
                    filtered = filter_hazards(
                        hazards,
                        city=report_city if report_city != "All India" else None,
                        severity=severity_filter if severity_filter else None,
                        start_date=start_date
                    )
                    
                    stats = compute_stats(filtered)
                    
                    st.markdown("#### Report Preview")
                    
                    preview_cols = st.columns(4)
                    with preview_cols[0]:
                        st.metric("Total", stats["total_hazards"])
                    with preview_cols[1]:
                        st.metric("High", stats["high_severity_count"])
                    with preview_cols[2]:
                        st.metric("Fixed", stats["fixed_count"])
                    with preview_cols[3]:
                        st.metric("Active", stats["active_issues"])
                    
                    # Download button
                    st.download_button(
                        label="📥 Download PDF Report",
                        data=pdf_bytes,
                        file_name=f"saferoute_report_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf",
                        mime="application/pdf",
                        type="primary"
                    )
                    
                except Exception as e:
                    st.error(f"Error generating PDF: {str(e)}")
    
    # ========== SUBMIT FORM ==========
    st.markdown("---")
    st.markdown("### Submit to Municipality")
    
    with st.form("submit_form"):
        st.markdown("""
        <div style="background: white; padding: 15px; border-radius: 8px; border: 1px solid #E5E7EB;">
            <p style="margin: 0 0 10px 0;"><strong>Submit Report to Municipal Authority</strong></p>
            <p style="font-size: 0.9rem; color: #666; margin: 0;">This will submit the generated report to the local municipality for action.</p>
        </div>
        """, unsafe_allow_html=True)
        
        submit_name = st.text_input("Your Name", placeholder="Name")
        submit_email = st.text_input("Email", placeholder="email@city.gov.in")
        submit_dept = st.selectbox("Department", options=["Roads", "Traffic", "Municipal", "Other"])
        submit_notes = st.text_area("Additional Notes", placeholder="Any additional information...")
        
        submit_btn = st.form_submit_button("📤 Submit Report", type="primary")
    
    if submit_btn:
        if not submit_name or not submit_email:
            st.error("Please fill in your name and email")
        else:
            # Show success message
            st.success(f"""
            ✅ **Report Submitted Successfully!**
            
            Thank you, {submit_name}! Your report has been submitted to the {submit_dept} department.
            
            A confirmation has been sent to {submit_email}.
            
            Reference ID: SR-{datetime.now().strftime('%Y%m%d%H%M%S')}
            """)
            
            st.balloons()
